### ISSUE TITLE
Mixing concerns and relation to other extensions

### ISSUE THREAD

**Issue by m-mohr** [CS-SI/eopf-stac-extension#2]
It looks like this extensions heavily mixes concerns: some fielda are about ids, some are instrument-related, same are processing-related, etc. It feels like everything that wasn't found yet in STAC was just put into one place. That's not a good idea, I think. Also, what's the relation with other extensions:

For example, pixel_classification seems related to the classification extension. It may need some improvements (https://github.com/stac-extensions/classification/issues/47) but generally, the changes should probably be made there instead of adding a new field.

Image size seems related to proj:shape. Shouldn't this be part of the bands, too?

eopf:instrument_mode seems related to sar:instrument_mode, but you may need that for additional types of instruments of course.
Same for eopf:instrument_swath, this should probably be proposed as a general purpose field, e.g. in an instrument extension?

Generally, many of these fields don't look overly EOPF specific. I'd try to avoid that to not run into a proprietary niche regarding tooling support.

**Comment by m-mohr** [comment]
Why not contribute these ideas to the existsing STAC extensions?

**Comment by cbouzina** [comment]
OK, I will do.

**Comment by cbouzina** [comment]
Do you think we could add instrument_mode and instrument_swath to the sat extension ?

**Comment by m-mohr** [comment]
Is instrument mode something that could also apply to non-satellited? It may be warranted in this case to create a new instrument extensions that defines these two fields.
In general, both fields would ideally define a voabulary of allowed values, otherwise the fields are pretty useless.

**Comment by cbouzina** [comment]
Final decisions taken in agreement with ESA and Copernicus
